name: ArborianQuests
author: JCThePants
main: com.jcwhatever.arborianquests.ArborianQuests
version: 0.0-beta
depend: [NucleusFramework]
commands:
    quests:
        aliases: [q, quest, arborianquests]
        description: Base command for Arborian Quests
        usage: |
            ERROR!